/* ============================================================================
   08. Tablas de staging (esquema stg) - poc_colombia

   Mismo layout de columnas que su tabla destino en dbo, pero SIN PK/FK/
   CHECK/IDENTITY -- el proceso de carga (Python) hace TRUNCATE + bulk insert
   aqui sin preocuparse de validaciones, y etl.usp_ReemplazarDimension /
   etl.usp_CargarFactoParticionado (09_sp_etl.sql) se encargan de mover los
   datos a dbo con las validaciones correspondientes.

   stg.tbl_Centros omite [Id] (es IDENTITY en dbo, se genera al insertar).
============================================================================ */

CREATE TABLE [stg].[tbl_Fechas] (
    [Mes] DATETIME2(0) NULL, [Num_Mes] INT NULL, [Mes_Reporte] INT NULL,
    [Mostrar_Vista_Años] INT NULL, [Mostrar_Vista_Histórica] INT NULL, [Mostrar] INT NULL,
    [LTM] INT NULL, [YTD] INT NULL, [Nom_Mes] NVARCHAR(20) NULL, [Año] INT NULL,
    [Trimestre] NVARCHAR(10) NULL, [Mes_12M] DATETIME2(0) NULL, [Mes_YTD] DATETIME2(0) NULL,
    [Mes_TIR] DATETIME2(0) NULL, [Año_Seguros] DATETIME2(0) NULL, [Año_Otras cuentas] DATETIME2(0) NULL
);
GO
CREATE TABLE [stg].[tbl_Niveles] ([Cod_Nivel] INT NULL, [Nom_Nivel] NVARCHAR(255) NULL);
GO
CREATE TABLE [stg].[tbl_Tiempos] ([Cod_Tiempo] INT NULL, [Nom_Tiempo] NVARCHAR(255) NULL);
GO
CREATE TABLE [stg].[tbl_Fondos] (
    [COD_FONDO] INT NULL, [COD_FONDO_FIDU] INT NULL, [ABREV_FONDO] NVARCHAR(255) NULL,
    [NOM_CORTO_FONDO] NVARCHAR(255) NULL, [NOM_FONDO] NVARCHAR(500) NULL,
    [FIDU] NVARCHAR(255) NULL, [FONDO] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Arrendatarios] (
    [NIT] NVARCHAR(20) NULL, [Nom_Arrend] NVARCHAR(255) NULL, [NomCorto_Arrend] NVARCHAR(255) NULL,
    [GRUPO_ECON] NVARCHAR(255) NULL, [Sector_Arrend] NVARCHAR(255) NULL,
    [Calif_Arrend] NVARCHAR(255) NULL, [Contacto_Arrend] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Cuentas] (
    [Cod_Cuenta] INT NULL, [Cuenta] NVARCHAR(255) NULL, [Signo] INT NULL,
    [Agrupación] NVARCHAR(255) NULL, [Agrup_Gastos] INT NULL, [Cálculo] INT NULL,
    [Por inmueble] INT NULL, [Divisor] FLOAT NULL, [Suma] INT NULL,
    [Unidades] INT NULL, [Ranking_Inm] INT NULL, [Mostrar_pie] INT NULL,
    [Dispers_EjeX] INT NULL, [Dispers_EjeY] INT NULL, [Dispers_Burb] INT NULL
);
GO
CREATE TABLE [stg].[tbl_Totales] (
    [Cod_Nivel] INT NULL, [Cod_Total] NVARCHAR(10) NULL, [Nom_Total] NVARCHAR(255) NULL,
    [Cruce1] NVARCHAR(255) NULL, [Cruce2] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Centros] (
    [Cod_Nivel] INT NULL, [Cod_Fondo] INT NULL, [Cod_Centro] NVARCHAR(20) NULL,
    [Nombre] NVARCHAR(255) NULL, [Tipologia] NVARCHAR(255) NULL, [Subtipologia] NVARCHAR(255) NULL,
    [Ubicacion] NVARCHAR(255) NULL, [Inmueble] NVARCHAR(255) NULL, [Arrendatario] NVARCHAR(255) NULL,
    [GRUPO_ECON] NVARCHAR(255) NULL, [Sector_Arrend] NVARCHAR(255) NULL, [Riesgo] NVARCHAR(255) NULL,
    [VENC_YR] INT NULL
);
GO
CREATE TABLE [stg].[tbl_Inmuebles] (
    [Fecha] DATETIME2(0) NULL, [Cod_Fondo] INT NULL, [Cod_Inm] DECIMAL(18,0) NULL,
    [Cod_Inm_Nue] DECIMAL(18,0) NULL, [Cod_Inm1] DECIMAL(18,0) NULL, [Cod_Inm1_Nue] DECIMAL(18,0) NULL,
    [Cod_Inm_TXT] NVARCHAR(255) NULL, [Nom_Inm] NVARCHAR(255) NULL, [Ubicacion] NVARCHAR(255) NULL,
    [Ubic_Pol_Inv] NVARCHAR(255) NULL, [Direccion] NVARCHAR(255) NULL, [Tipologia] NVARCHAR(255) NULL,
    [Tipologia_Cons] NVARCHAR(255) NULL, [Subtipologia] NVARCHAR(255) NULL, [Estado] NVARCHAR(255) NULL,
    [Tipo_Riesgo] NVARCHAR(255) NULL, [Georef] NVARCHAR(255) NULL, [Coordenadas] NVARCHAR(255) NULL,
    [Latitud] FLOAT NULL, [Longitud] FLOAT NULL, [Titularidad] NVARCHAR(255) NULL,
    [Subtipologia3] NVARCHAR(255) NULL, [Certificacion] NVARCHAR(255) NULL,
    [Año_de_contruccion] NVARCHAR(255) NULL, [Conteo] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Contratos] (
    [FECHA] DATETIME2(0) NULL, [COD_FONDO] INT NULL, [ESTADO] NVARCHAR(30) NULL,
    [COD_CTR] NVARCHAR(20) NULL, [NIT] NVARCHAR(20) NULL, [NOM_ARREND] NVARCHAR(255) NULL,
    [COD_INM] DECIMAL(18,0) NULL, [DET_INM] NVARCHAR(255) NULL, [GLA] FLOAT NULL,
    [Tipologia] NVARCHAR(255) NULL, [Fec_Inicio] DATETIME2(0) NULL, [Fec_Fin] DATETIME2(0) NULL,
    [IncremCanon] NVARCHAR(255) NULL
);
GO

/* -- Facts "Valores" (mismo layout, ver 04_facts_valores.sql) -- */
CREATE TABLE [stg].[tbl_Valores] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Fondo] INT NULL,
    [Cod_Nivel] INT NULL, [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Valor_Libros] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Gastos_Otros] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Fondo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Gastos] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Avaluos] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Ingresos] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Nexus] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Fondo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_Viva_Malls] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_GLA_2008_2023] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_2011_2023_PYG] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Valores_2011_2023_VlrLibros] (
    [Fecha] DATETIME2(0) NULL, [Cod_Tiempo] INT NULL, [Cod_Nivel] INT NULL,
    [Cod_Centro] NVARCHAR(20) NULL, [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Pagos_Inmuebles] (
    [Fecha] DATETIME2(0) NULL, [Fecha_TRN] DATETIME2(0) NULL, [Cod_Inm] DECIMAL(18,0) NULL,
    [Cod_Cuenta] INT NULL, [Valor] FLOAT NULL
);
GO

/* -- Submodelo EEFF 351 (ver 05_eeff_351.sql) -- */
CREATE TABLE [stg].[tbl_Cuentas_EEFF] (
    [COD_CTA] DECIMAL(18,0) NULL, [NOM_CTA] NVARCHAR(255) NULL, [SIGNO_CTA] INT NULL,
    [SIGNO_REPORTE] INT NULL, [TIPO_CTA] INT NULL, [SUMA] INT NULL, [Clasif_Contable] NVARCHAR(255) NULL,
    [COD_AGRUP] NVARCHAR(50) NULL, [NOM_AGRUP] NVARCHAR(255) NULL,
    [Cod_Nivel1] NVARCHAR(50) NULL, [Nom_Nivel1] NVARCHAR(255) NULL,
    [Cod_Nivel2] NVARCHAR(50) NULL, [Nom_Nivel2] NVARCHAR(255) NULL,
    [Cod_Nivel3] NVARCHAR(50) NULL, [Nom_Nivel3] NVARCHAR(255) NULL,
    [Cod_Nivel4] NVARCHAR(50) NULL, [Nom_Nivel4] NVARCHAR(255) NULL,
    [Cod_Nivel5] NVARCHAR(50) NULL, [Nom_Nivel5] NVARCHAR(255) NULL,
    [Cod_Nivel3A] NVARCHAR(50) NULL, [Nom_Nivel3A] NVARCHAR(255) NULL,
    [Cod_Nivel4A] NVARCHAR(50) NULL, [Nom_Nivel4A] NVARCHAR(255) NULL,
    [Cod_Nivel5A] NVARCHAR(50) NULL, [Nom_Nivel5A] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_EEFF] (
    [FECHA] DATETIME2(0) NULL, [COD_FONDO] INT NULL, [COD_CTA] DECIMAL(18,0) NULL,
    [NIT_TERCERO] DECIMAL(18,0) NULL, [SALDO] FLOAT NULL
);
GO
CREATE TABLE [stg].[F351] (
    [FECHA] DATETIME2(0) NULL, [INMUEBLE] NVARCHAR(255) NULL, [matrícula] NVARCHAR(50) NULL,
    [Unidad de Captura] FLOAT NULL, [No asignado por la entidad] FLOAT NULL,
    [Fecha emisión] FLOAT NULL, [Valor nominal] FLOAT NULL,
    [Valor de compra moneda original] FLOAT NULL, [Valor de compra en pesos] FLOAT NULL,
    [Vr mercado o valor presente en $] FLOAT NULL, [Campo11] NVARCHAR(255) NULL,
    [Campo12] FLOAT NULL, [Campo13] FLOAT NULL, [Campo14] FLOAT NULL, [F15] FLOAT NULL
);
GO
CREATE TABLE [stg].[VL_CentralPoint] (
    [FECHA] DATETIME2(0) NULL, [VLR_FINAL_E1] FLOAT NULL, [VLR_FINAL_E2] FLOAT NULL,
    [VLR_E1] FLOAT NULL, [VLR_E2] FLOAT NULL, [MVA] FLOAT NULL,
    [TOTAL_ACTIVOS_PA] FLOAT NULL, [PASIVO_PA] FLOAT NULL, [ANT_DF] FLOAT NULL,
    [TOTAL] FLOAT NULL, [351] FLOAT NULL, [DIF] FLOAT NULL,
    [UVR_E1] FLOAT NULL, [UVR_E2] FLOAT NULL, [UVR_E1_#2] FLOAT NULL,
    [UVR_E2_#2] FLOAT NULL, [AVAL_E1] FLOAT NULL, [AVAL_E2] FLOAT NULL,
    [VLR_AVAL_E1] FLOAT NULL, [VLR_AVAL_E2] FLOAT NULL
);
GO
CREATE TABLE [stg].[VL_Disp_xa_Venta] (
    [FECHA] DATETIME2(0) NULL, [COD_INM] DECIMAL(18,0) NULL, [DESCR_INM] NVARCHAR(255) NULL,
    [VALOR] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_ValorLibros_xInmueble] (
    [DESCR] NVARCHAR(255) NULL, [FECHA] DATETIME2(0) NULL, [Cod_Inm] DECIMAL(18,0) NULL,
    [COD_CTA] DECIMAL(18,0) NULL, [VALOR] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_Cruce_SIF] (
    [Cod_Cta] DECIMAL(18,0) NULL, [Nom_Cta] NVARCHAR(255) NULL, [Grupo_Cuenta] NVARCHAR(100) NULL,
    [NIT_Tercero] DECIMAL(18,0) NULL, [Nom_Tercero] NVARCHAR(255) NULL,
    [Cod_SIF] NVARCHAR(50) NULL, [Nom_SIF] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Cruce351] (
    [COD_ASIGN_FIDU] DECIMAL(18,0) NULL, [Descripción351] NVARCHAR(100) NULL, [Cod_Inm] DECIMAL(18,0) NULL
);
GO
CREATE TABLE [stg].[tbl_Usuarios] ([Usuario] NVARCHAR(100) NULL);
GO

/* -- Detalle contratos/inmuebles (ver 11_detalle_contratos_inmuebles.sql) -- */
CREATE TABLE [stg].[tbl_Contratos_Detalle] (
    [Origen_Hoja] NVARCHAR(20) NULL, [FECHA] DATETIME2(0) NULL, [COD] NVARCHAR(20) NULL,
    [COD_Nuevo] FLOAT NULL, [ARRENDATARIO] NVARCHAR(255) NULL, [CIUDAD DEL PREDIO] NVARCHAR(255) NULL,
    [TIPOLOGÍA INMUEBLE] NVARCHAR(255) NULL, [DESCRIPCIÓN] NVARCHAR(255) NULL,
    [TIPO DE CONTRATO] NVARCHAR(MAX) NULL, [ÁREA RENTABLE CONTRATO ARRENDAMIENTO] FLOAT NULL,
    [ÚLTIMO CANON] FLOAT NULL, [CANON M2] FLOAT NULL, [FECHA INICIO CONTRATO] DATETIME2(0) NULL,
    [FECHA INICIO COBRO CANON] DATETIME2(0) NULL, [DURACIÓN AÑOS ARRENDAMIENTO] FLOAT NULL,
    [FECHA FINALIZACIÓN CONTRATO INICIAL] DATETIME2(0) NULL,
    [FECHA FIN CONTRATO (incluye prórrogas/renovaciones)] DATETIME2(0) NULL,
    [MES DE AJUSTE ANUAL] FLOAT NULL, [INCREMENTO ANUAL SOBRE IPC] NVARCHAR(MAX) NULL,
    [INCREMENTO ANUAL COMO VECES IPC] FLOAT NULL, [DETALLE INCREMENTO] NVARCHAR(MAX) NULL,
    [CANON VARIABLE] NVARCHAR(255) NULL, [CLÁUSULA INCREMENTO DE CANON] NVARCHAR(MAX) NULL,
    [PREAVISO EN MESES TÉRMINO INICIAL] FLOAT NULL, [PREAVISO PRÓRROGA / RENOVACIÓN] FLOAT NULL,
    [PRÓRROGAS / RENOVACIONES] NVARCHAR(MAX) NULL,
    [CLÁUSULA CONDICIONES PRÓRROGAS / RENOVACIONES] NVARCHAR(MAX) NULL,
    [AÑOS POR PRÓRROGA/RENOVACIÓN] FLOAT NULL, [NÚMERO DE PRÓRRGAS / RENOVACIONES] NVARCHAR(255) NULL,
    [FECHA PRÓRROGA / RENOVACIÓN] NVARCHAR(255) NULL, [FECHA PREAVISO] FLOAT NULL,
    [CLÁUSULA SALIDA ANTICIPADA] NVARCHAR(MAX) NULL,
    [FECHA POSIBLE DE TERMINACIÓN ANTICIPADA] NVARCHAR(255) NULL,
    [CLÁUSULA REVISIÓN CONDICIONES ECONÓMICAS] NVARCHAR(MAX) NULL,
    [PISO / TECHO RENEGOCIACIÓN CANON] NVARCHAR(MAX) NULL,
    [REVISIÓN CANON TÉRMINO INICIAL (AÑOS)] FLOAT NULL,
    [REVISIÓN CANON PRORROGA / RENOVACIÓN (AÑOS)] FLOAT NULL,
    [PRÓXIMA FECHA REVISIÓN DE CONDICIONES ECONÓMICAS] FLOAT NULL,
    [MESES PARA REVISIÓN DE CONDICIONES ECONÓMICAS] FLOAT NULL,
    [ACTIVACIÓN FECHA REVISIÓN DE CONDICIONES ECONÓMICAS] FLOAT NULL,
    [CONDICIONES ESPECIALES DE CANON] NVARCHAR(MAX) NULL, [CONDICIONES DE FACTURACIÓN] NVARCHAR(MAX) NULL,
    [DIA DE INCREMENTO] NVARCHAR(255) NULL, [DIAS DE VENCIMIENTO DE FACTURA] NVARCHAR(255) NULL,
    [DIAS DE VENCIMIENTO DE FACTURA (HÁBIL O CALENDARIO)] NVARCHAR(255) NULL,
    [BASE DE FACTURACIÓN] NVARCHAR(MAX) NULL, [PERIODICIDAD DE LA FACTURACION] NVARCHAR(MAX) NULL,
    [FORMULA DE INCREMENTO] NVARCHAR(MAX) NULL, [TIPO DE IPC INCREMENTO] NVARCHAR(255) NULL,
    [CANON MOBILIARIO (SI APLICA)] NVARCHAR(MAX) NULL, [CANON AVISO (SI APLICA)] NVARCHAR(MAX) NULL,
    [REPARACIONES NECESARIAS] NVARCHAR(MAX) NULL, [REPARACIONES LOCATIVAS] NVARCHAR(MAX) NULL,
    [MANTENIMIENTO DEL INMUEBLE] NVARCHAR(MAX) NULL, [REPOSICIONES MUEBLES Y EQUIPOS] NVARCHAR(MAX) NULL,
    [CUOTAS DE ADMINISTRACIÓN ORDINARIAS] NVARCHAR(MAX) NULL,
    [CUOTAS DE ADMINISTRACIÓN EXTRAORDINARIAS] NVARCHAR(MAX) NULL,
    [SERVICIOS PÚBLICOS] NVARCHAR(MAX) NULL, [SEGUROS INMUEBLE] NVARCHAR(MAX) NULL,
    [GARANTÍAS] NVARCHAR(MAX) NULL, [DETALLE GARANTÍAS] NVARCHAR(MAX) NULL, [COVENANTS] NVARCHAR(MAX) NULL,
    [OTROSÍES] FLOAT NULL, [FECHA OTROSÍ] FLOAT NULL, [TIPO DE PERSONA] NVARCHAR(255) NULL,
    [NIT ARRENDATARIO] NVARCHAR(20) NULL, [COD INMUEBLE] FLOAT NULL, [COD_INMUEBLE_Nuevo] FLOAT NULL,
    [INMUEBLE CONSOLIDADO] NVARCHAR(255) NULL, [ENTIDAD ESTATAL] NVARCHAR(255) NULL,
    [SE FACTURA CON IVA O NO] NVARCHAR(255) NULL, [OBSERVACIONES] NVARCHAR(MAX) NULL,
    [ESTANDARIZAR ARCHIVOS DIGITALES] NVARCHAR(MAX) NULL, [MOBILIARIO Y OBRA BLANCA] NVARCHAR(MAX) NULL,
    [CANON DE MERCADO] NVARCHAR(MAX) NULL, [SECTOR ECONÓMICO] NVARCHAR(255) NULL,
    [VALIDACIÓN ÁREA DE CONTRATO ARRENDAMIENTO] NVARCHAR(MAX) NULL, [DESCRIPCIÓN ANTIGUA] NVARCHAR(255) NULL,
    [DIRECCIÓN] NVARCHAR(255) NULL, [OBSERVACIONES REVISIÓN DE CONTRATO] NVARCHAR(MAX) NULL
);
GO
CREATE TABLE [stg].[tbl_Contratos_Otros_Fondos] (
    [ESTADO] NVARCHAR(30) NULL, [COD_CTR] NVARCHAR(20) NULL, [NIT] NVARCHAR(20) NULL,
    [Nom_Arrend] NVARCHAR(255) NULL, [Cod_Inm] INT NULL, [Nom_Inm] NVARCHAR(255) NULL,
    [Det_Inm] NVARCHAR(255) NULL, [GLA] FLOAT NULL, [Tipologia] NVARCHAR(255) NULL,
    [Fec_Inicio] DATETIME2(0) NULL, [Fec_Fin] DATETIME2(0) NULL, [IncremCanon] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Contratos_Restituidos_OtrosFondos] (
    [FECHA] DATETIME2(0) NULL, [COD_CTR] NVARCHAR(20) NULL, [NIT] NVARCHAR(20) NULL,
    [Nom_Arrend] NVARCHAR(255) NULL, [Cod_Inm] INT NULL, [Nom_Inm] NVARCHAR(255) NULL,
    [Det_Inm] NVARCHAR(255) NULL, [GLA] FLOAT NULL, [Tipologia] NVARCHAR(255) NULL,
    [UBICACION] NVARCHAR(255) NULL, [Fec_Inicio] DATETIME2(0) NULL, [Fec_Fin] DATETIME2(0) NULL,
    [IncremCanon] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Inmuebles_Estrategia] (
    [Cod_Inm] INT NULL, [Nom_Inm] NVARCHAR(255) NULL, [Desc_Inm] NVARCHAR(255) NULL,
    [Ubicacion] NVARCHAR(255) NULL, [Ubic_Pol_Inv] NVARCHAR(255) NULL, [Direccion] NVARCHAR(255) NULL,
    [Tipologia] NVARCHAR(255) NULL, [GLA] FLOAT NULL, [Estado] NVARCHAR(255) NULL,
    [Origen] NVARCHAR(255) NULL, [FechaVenta] DATETIME2(0) NULL, [ValorVenta] FLOAT NULL,
    [Georef] NVARCHAR(500) NULL, [Coordenadas] NVARCHAR(255) NULL, [Latitud] FLOAT NULL,
    [Longitud] FLOAT NULL, [En_PA] NVARCHAR(10) NULL, [Certificacion] NVARCHAR(255) NULL,
    [Estrategia] NVARCHAR(255) NULL, [Subtipologia] NVARCHAR(255) NULL, [Destinacion] NVARCHAR(255) NULL,
    [Operacion] NVARCHAR(255) NULL, [PlanCortoPlazo] NVARCHAR(255) NULL, [Riesgo] NVARCHAR(255) NULL,
    [Accion] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Inmuebles_Compras] (
    [Cod_Inm] NVARCHAR(20) NULL, [Cod_Inm_Nuevo] INT NULL, [Nom_Inm] NVARCHAR(255) NULL,
    [Tipologia] NVARCHAR(255) NULL, [FechaCompra] DATETIME2(0) NULL, [ValorCompra] FLOAT NULL
);
GO
CREATE TABLE [stg].[tbl_MI] (
    [MI_NUM] INT NULL, [MI_TXT] NVARCHAR(255) NULL, [DESCRIPCION] NVARCHAR(255) NULL, [COD_INM] INT NULL
);
GO
CREATE TABLE [stg].[tbl_Inmuebles_MI_Contratos] (
    [Cod_Inm] INT NULL, [Cod_Contrato] NVARCHAR(20) NULL, [Arrendatario] NVARCHAR(255) NULL,
    [Matricula] NVARCHAR(50) NULL, [Descripcion] NVARCHAR(255) NULL
);
GO
CREATE TABLE [stg].[tbl_Inmuebles_Otros] (
    [Cod_Inm] INT NULL, [Nom_Inm] NVARCHAR(255) NULL, [Tipologia] NVARCHAR(255) NULL
);
GO
